server:
  port: 10001

spring:
  application:
    name: production-of-goods

  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/production_of_goods
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    open-in-view: false  # сессия живет в рамках всего http запроса
    hibernate:
      ddl-auto: validate  # validate - проверяет схему, но не меняет ее
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
#        format_sql: true
    database: postgresql

  jdbc:
    template:
      fetch-size: 100  # размер выборки

logging:
  level:
    com.pot.app.productionofgoods.service.work: INFO
#    org.flywaydb: DEBUG
    org.springframework.jdbc: DEBUG


## Включить DEBUG для всего приложения
#  logging.level.root=DEBUG
#
#  # Или только для конкретных пакетов
#  logging.level.com.example.project.service=DEBUG
#  logging.level.com.example.project.repository=DEBUG
#
#  # Можно комбинировать
#  logging.level.root=INFO
#  logging.level.com.example.project=DEBUG


